name: Build & Deploy

on:
  push:
    branches: master

jobs:
  build:
    name: build with sm${{ matrix.sm_version }} on ${{ matrix.os_short }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        sm_version:
          - "1.8"
          - "1.9"
          - "1.10"
          - "latest"
  
        include:
          - sm_version: latest
            sm_branch: master
            
          - sm_version: "1.8"
            sm_branch: "1.8-dev"
            
          - sm_version: "1.9"
            sm_branch: "1.9-dev"
            
          - sm_version: "1.10"
            sm_branch: "1.10-dev"
          
          - os: ubuntu-latest
            os_short: linux
          
    steps:
      - name: Install (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y clang g++-multilib
          echo "::set-env name=CC::clang"
          echo "::set-env name=CXX::clang++"
        
      - name: Checking out SourceMod
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/sourcemod
          ref: ${{ matrix.sm_branch }}
          path: sourcemod-${{ matrix.sm_version }}
          submodules: recursive
        
      - name: Checking out MM:Source
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/metamod-source
          ref: master
          path: metamod-latest
        
      - name: Checking out AMBuild
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/ambuild
          path: ambuild
        
      - name: Set up Python
        uses: actions/setup-python@v2
        
      - name: Setting up ambuild
        working-directory: ambuild
        run: python setup.py install
        
      - name: Checking out hl2sdk-l4d2
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/hl2sdk
          ref: l4d2
          path: hl2sdk-l4d2
        
      - name: Checking out hl2sdk-l4d
        uses: actions/checkout@v2
        with:
          repository: alliedmodders/hl2sdk
          ref: l4d
          path: hl2sdk-l4d
        
      - name: Checking out own repository
        uses: actions/checkout@v2
        with:
          path: sourcetvsupport
        
      - name: Compile SourceTVSupport files
        working-directory: sourcetvsupport
        run: |
          mkdir build
          cd build
          python ../configure.py --sm-path="${{ github.workspace }}/sourcemod-${{ matrix.sm_version }}" --mms-path="${{ github.workspace }}/metamod-latest"
          ambuild
        
      - name: Uploading package
        uses: actions/upload-artifact@v2
        with:
          name: sourcetvsupport-sm-${{ matrix.sm_version }}-${{ matrix.os_short }}
          path: sourcetvsupport/build/package
